### ISSUE TITLE
IPFS Cat fails to parse ipns

### ISSUE THREAD

**Issue by travisperson** [jbenet/go-ipfs#922] opened 2015-03-12 19:59 UTC
```
$ ipfs cat /ipns/ipfs.git.sexy
Error: multihash length inconsistent: &{124  132 [104]}
```

**Comment by jbenet** [comment] 2015-03-13 09:41
we need to make sure we're using proper `<ipfs-path>` and `<ipns-path>` everywhere.

**Comment by whyrusleeping** [comment] 2015-03-28 08:52
This is a duplicate of #750

**Closed by whyrusleeping** 2015-03-28 08:52 UTC
